// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/job/service.proto

package job

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	protobuf "github.com/oojob/protobuf"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	Identity             *protobuf.Identifier `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Employment           string               `protobuf:"bytes,2,opt,name=employment,proto3" json:"employment,omitempty"`
	Salary               *protobuf.Range      `protobuf:"bytes,3,opt,name=salary,proto3" json:"salary,omitempty"`
	Experience           *protobuf.Range      `protobuf:"bytes,4,opt,name=experience,proto3" json:"experience,omitempty"`
	Time                 *protobuf.Time       `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	Skills               []string             `protobuf:"bytes,6,rep,name=skills,proto3" json:"skills,omitempty"`
	WorkingHours         string               `protobuf:"bytes,7,opt,name=working_hours,json=workingHours,proto3" json:"working_hours,omitempty"`
	Status               string               `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Qualification        []string             `protobuf:"bytes,9,rep,name=qualification,proto3" json:"qualification,omitempty"`
	Place                *protobuf.Place      `protobuf:"bytes,10,opt,name=place,proto3" json:"place,omitempty"`
	Metadata             *protobuf.Metadata   `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Applicants           *protobuf.Applicant  `protobuf:"bytes,12,opt,name=applicants,proto3" json:"applicants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cffff2135115270, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetIdentity() *protobuf.Identifier {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Job) GetEmployment() string {
	if m != nil {
		return m.Employment
	}
	return ""
}

func (m *Job) GetSalary() *protobuf.Range {
	if m != nil {
		return m.Salary
	}
	return nil
}

func (m *Job) GetExperience() *protobuf.Range {
	if m != nil {
		return m.Experience
	}
	return nil
}

func (m *Job) GetTime() *protobuf.Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Job) GetSkills() []string {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *Job) GetWorkingHours() string {
	if m != nil {
		return m.WorkingHours
	}
	return ""
}

func (m *Job) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Job) GetQualification() []string {
	if m != nil {
		return m.Qualification
	}
	return nil
}

func (m *Job) GetPlace() *protobuf.Place {
	if m != nil {
		return m.Place
	}
	return nil
}

func (m *Job) GetMetadata() *protobuf.Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Job) GetApplicants() *protobuf.Applicant {
	if m != nil {
		return m.Applicants
	}
	return nil
}

type CreateJobReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Descriptioon         string   `protobuf:"bytes,2,opt,name=descriptioon,proto3" json:"descriptioon,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobReq) Reset()         { *m = CreateJobReq{} }
func (m *CreateJobReq) String() string { return proto.CompactTextString(m) }
func (*CreateJobReq) ProtoMessage()    {}
func (*CreateJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cffff2135115270, []int{1}
}

func (m *CreateJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobReq.Unmarshal(m, b)
}
func (m *CreateJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobReq.Marshal(b, m, deterministic)
}
func (m *CreateJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobReq.Merge(m, src)
}
func (m *CreateJobReq) XXX_Size() int {
	return xxx_messageInfo_CreateJobReq.Size(m)
}
func (m *CreateJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobReq proto.InternalMessageInfo

func (m *CreateJobReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateJobReq) GetDescriptioon() string {
	if m != nil {
		return m.Descriptioon
	}
	return ""
}

func (m *CreateJobReq) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type CreateJobRes struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobRes) Reset()         { *m = CreateJobRes{} }
func (m *CreateJobRes) String() string { return proto.CompactTextString(m) }
func (*CreateJobRes) ProtoMessage()    {}
func (*CreateJobRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cffff2135115270, []int{2}
}

func (m *CreateJobRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRes.Unmarshal(m, b)
}
func (m *CreateJobRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRes.Marshal(b, m, deterministic)
}
func (m *CreateJobRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRes.Merge(m, src)
}
func (m *CreateJobRes) XXX_Size() int {
	return xxx_messageInfo_CreateJobRes.Size(m)
}
func (m *CreateJobRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRes proto.InternalMessageInfo

func (m *CreateJobRes) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CreateJobRes) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Job)(nil), "job.Job")
	proto.RegisterType((*CreateJobReq)(nil), "job.CreateJobReq")
	proto.RegisterType((*CreateJobRes)(nil), "job.CreateJobRes")
}

func init() {
	proto.RegisterFile("services/job/service.proto", fileDescriptor_8cffff2135115270)
}

var fileDescriptor_8cffff2135115270 = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x95, 0xbf, 0xc4, 0xd3, 0x14, 0x89, 0x39, 0xa0, 0x95, 0x0f, 0x10, 0xa5, 0x2d, 0x8a,
	0x90, 0x70, 0xa0, 0x95, 0x2a, 0x6e, 0x50, 0x95, 0x43, 0x89, 0x84, 0x84, 0x16, 0x24, 0x8e, 0x68,
	0xed, 0x4c, 0xe2, 0x6d, 0x6c, 0xaf, 0xe3, 0x5d, 0x03, 0x79, 0x0c, 0x9e, 0x8d, 0x17, 0x42, 0xde,
	0x6c, 0xd2, 0x44, 0x28, 0x6e, 0x2f, 0xdc, 0x3c, 0xb3, 0xbf, 0xef, 0x1b, 0xef, 0xe8, 0x5b, 0xf0,
	0x35, 0x15, 0x3f, 0x64, 0x44, 0x7a, 0x7c, 0xab, 0xc2, 0xb1, 0x2b, 0x82, 0xbc, 0x50, 0x46, 0x61,
	0xeb, 0x56, 0x85, 0xfe, 0xd9, 0x5c, 0x9a, 0xb8, 0x0c, 0x83, 0x48, 0xa5, 0x63, 0xa5, 0x2a, 0xc8,
	0x1e, 0x86, 0xe5, 0x6c, 0x9c, 0x27, 0x62, 0xc3, 0xfa, 0xa3, 0xc3, 0x58, 0x4a, 0x46, 0x4c, 0x85,
	0x11, 0x8e, 0x3c, 0x3d, 0x4c, 0x1a, 0x99, 0x6e, 0xfc, 0x5e, 0x1c, 0xa6, 0xf4, 0x4a, 0x1b, 0x4a,
	0xef, 0xe7, 0x62, 0x12, 0x89, 0x89, 0x1d, 0xf7, 0xf2, 0x30, 0x27, 0xf2, 0x3c, 0x91, 0x91, 0xc8,
	0x8c, 0x5e, 0xb3, 0xc3, 0x3f, 0x6d, 0x68, 0x4d, 0x54, 0x88, 0x57, 0xd0, 0x93, 0x53, 0xca, 0x8c,
	0x34, 0x2b, 0xd6, 0x18, 0x34, 0x46, 0x47, 0xe7, 0x67, 0xc1, 0x9d, 0x4d, 0x60, 0x6d, 0x82, 0x8d,
	0x4d, 0xf0, 0xd1, 0xa2, 0x33, 0x49, 0x05, 0xdf, 0xca, 0xf0, 0x19, 0x00, 0xa5, 0x79, 0xa2, 0x56,
	0x29, 0x65, 0x86, 0x35, 0x07, 0x8d, 0x91, 0xc7, 0x77, 0x3a, 0xf8, 0x16, 0xba, 0x5a, 0x24, 0xa2,
	0x58, 0xb1, 0x96, 0x1d, 0x30, 0xa8, 0x19, 0xc0, 0x45, 0x36, 0x27, 0xee, 0x78, 0x7c, 0x0f, 0x40,
	0xbf, 0x72, 0x2a, 0x24, 0x65, 0x11, 0xb1, 0xf6, 0x03, 0xd5, 0x3b, 0x1a, 0xbc, 0x80, 0x76, 0xb5,
	0x70, 0xd6, 0xb1, 0xda, 0xe7, 0x35, 0xda, 0xaf, 0x32, 0x25, 0x6e, 0x61, 0x7c, 0x0a, 0x5d, 0xbd,
	0x90, 0x49, 0xa2, 0x59, 0x77, 0xd0, 0x1a, 0x79, 0xdc, 0x55, 0x78, 0x02, 0xc7, 0x3f, 0x55, 0xb1,
	0x90, 0xd9, 0xfc, 0x7b, 0xac, 0xca, 0x42, 0xb3, 0x47, 0xf6, 0xae, 0x7d, 0xd7, 0xbc, 0xa9, 0x7a,
	0x56, 0x6c, 0x84, 0x29, 0x35, 0xeb, 0xd9, 0x53, 0x57, 0xe1, 0x29, 0x1c, 0x2f, 0x4b, 0x91, 0xc8,
	0x99, 0x8c, 0x84, 0x91, 0x2a, 0x63, 0x9e, 0xf5, 0xde, 0x6f, 0xe2, 0x25, 0x74, 0x6c, 0xe2, 0x18,
	0xdc, 0x7b, 0xd9, 0xcf, 0x15, 0xc7, 0xd7, 0x38, 0xbe, 0x83, 0xde, 0x26, 0x82, 0xec, 0xc8, 0x4a,
	0x4f, 0x6a, 0xa4, 0x9f, 0x1c, 0xca, 0xb7, 0x22, 0xfc, 0x00, 0x70, 0x97, 0x11, 0xd6, 0xb7, 0x16,
	0xa7, 0x35, 0x16, 0x57, 0x1b, 0x98, 0xef, 0xe8, 0x86, 0x21, 0xf4, 0xaf, 0x0b, 0x12, 0x86, 0x26,
	0x2a, 0xe4, 0xb4, 0x44, 0x84, 0x76, 0x26, 0x52, 0xb2, 0xc9, 0xf2, 0xb8, 0xfd, 0xc6, 0x21, 0xf4,
	0xa7, 0xa4, 0xa3, 0x42, 0xe6, 0x46, 0x2a, 0x95, 0xb9, 0xc0, 0xec, 0xf5, 0xd0, 0x87, 0x5e, 0x24,
	0x0c, 0xcd, 0x95, 0x0b, 0x8d, 0xc7, 0xb7, 0xf5, 0xf0, 0x72, 0x6f, 0xc6, 0xee, 0xc2, 0xab, 0x29,
	0xbd, 0xed, 0xc2, 0x1f, 0x43, 0x53, 0x4e, 0x9d, 0x7b, 0x53, 0x4e, 0xcf, 0x7f, 0x37, 0x01, 0x26,
	0x2a, 0xfc, 0xb2, 0x7e, 0xfe, 0xf8, 0x06, 0xbc, 0xad, 0x0d, 0x3e, 0x09, 0xaa, 0xcb, 0xed, 0xfe,
	0xba, 0xff, 0x4f, 0x4b, 0xe3, 0x0c, 0x3a, 0xd7, 0x31, 0x45, 0x0b, 0x7c, 0x55, 0xb3, 0x98, 0x1b,
	0xfb, 0x22, 0x2d, 0xc7, 0x69, 0x59, 0x92, 0x36, 0x7e, 0xf0, 0x50, 0x5c, 0xe7, 0x2a, 0xd3, 0x84,
	0x31, 0x74, 0xbe, 0x09, 0x13, 0xc5, 0xff, 0x79, 0xce, 0xeb, 0x46, 0xd8, 0xb5, 0xe7, 0x17, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x68, 0x00, 0x36, 0x95, 0x22, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobServiceClient interface {
	CreateJob(ctx context.Context, in *CreateJobReq, opts ...grpc.CallOption) (*CreateJobRes, error)
	Check(ctx context.Context, in *protobuf.HealthCheckRequest, opts ...grpc.CallOption) (*protobuf.HealthCheckResponse, error)
	Watch(ctx context.Context, in *protobuf.HealthCheckRequest, opts ...grpc.CallOption) (JobService_WatchClient, error)
}

type jobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobServiceClient(cc grpc.ClientConnInterface) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) CreateJob(ctx context.Context, in *CreateJobReq, opts ...grpc.CallOption) (*CreateJobRes, error) {
	out := new(CreateJobRes)
	err := c.cc.Invoke(ctx, "/job.JobService/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) Check(ctx context.Context, in *protobuf.HealthCheckRequest, opts ...grpc.CallOption) (*protobuf.HealthCheckResponse, error) {
	out := new(protobuf.HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/job.JobService/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) Watch(ctx context.Context, in *protobuf.HealthCheckRequest, opts ...grpc.CallOption) (JobService_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_JobService_serviceDesc.Streams[0], "/job.JobService/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobServiceWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JobService_WatchClient interface {
	Recv() (*protobuf.HealthCheckResponse, error)
	grpc.ClientStream
}

type jobServiceWatchClient struct {
	grpc.ClientStream
}

func (x *jobServiceWatchClient) Recv() (*protobuf.HealthCheckResponse, error) {
	m := new(protobuf.HealthCheckResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// JobServiceServer is the server API for JobService service.
type JobServiceServer interface {
	CreateJob(context.Context, *CreateJobReq) (*CreateJobRes, error)
	Check(context.Context, *protobuf.HealthCheckRequest) (*protobuf.HealthCheckResponse, error)
	Watch(*protobuf.HealthCheckRequest, JobService_WatchServer) error
}

// UnimplementedJobServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJobServiceServer struct {
}

func (*UnimplementedJobServiceServer) CreateJob(ctx context.Context, req *CreateJobReq) (*CreateJobRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJob not implemented")
}
func (*UnimplementedJobServiceServer) Check(ctx context.Context, req *protobuf.HealthCheckRequest) (*protobuf.HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedJobServiceServer) Watch(req *protobuf.HealthCheckRequest, srv JobService_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}

func RegisterJobServiceServer(s *grpc.Server, srv JobServiceServer) {
	s.RegisterService(&_JobService_serviceDesc, srv)
}

func _JobService_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.JobService/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CreateJob(ctx, req.(*CreateJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protobuf.HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.JobService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).Check(ctx, req.(*protobuf.HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(protobuf.HealthCheckRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobServiceServer).Watch(m, &jobServiceWatchServer{stream})
}

type JobService_WatchServer interface {
	Send(*protobuf.HealthCheckResponse) error
	grpc.ServerStream
}

type jobServiceWatchServer struct {
	grpc.ServerStream
}

func (x *jobServiceWatchServer) Send(m *protobuf.HealthCheckResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _JobService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "job.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _JobService_CreateJob_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _JobService_Check_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _JobService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/job/service.proto",
}
