// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package job

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateJobReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Descriptioon         string   `protobuf:"bytes,2,opt,name=descriptioon,proto3" json:"descriptioon,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobReq) Reset()         { *m = CreateJobReq{} }
func (m *CreateJobReq) String() string { return proto.CompactTextString(m) }
func (*CreateJobReq) ProtoMessage()    {}
func (*CreateJobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *CreateJobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobReq.Unmarshal(m, b)
}
func (m *CreateJobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobReq.Marshal(b, m, deterministic)
}
func (m *CreateJobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobReq.Merge(m, src)
}
func (m *CreateJobReq) XXX_Size() int {
	return xxx_messageInfo_CreateJobReq.Size(m)
}
func (m *CreateJobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobReq proto.InternalMessageInfo

func (m *CreateJobReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateJobReq) GetDescriptioon() string {
	if m != nil {
		return m.Descriptioon
	}
	return ""
}

func (m *CreateJobReq) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type CreateJobRes struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobRes) Reset()         { *m = CreateJobRes{} }
func (m *CreateJobRes) String() string { return proto.CompactTextString(m) }
func (*CreateJobRes) ProtoMessage()    {}
func (*CreateJobRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *CreateJobRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRes.Unmarshal(m, b)
}
func (m *CreateJobRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRes.Marshal(b, m, deterministic)
}
func (m *CreateJobRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRes.Merge(m, src)
}
func (m *CreateJobRes) XXX_Size() int {
	return xxx_messageInfo_CreateJobRes.Size(m)
}
func (m *CreateJobRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRes proto.InternalMessageInfo

func (m *CreateJobRes) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CreateJobRes) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateJobReq)(nil), "job.CreateJobReq")
	proto.RegisterType((*CreateJobRes)(nil), "job.CreateJobRes")
}

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x41, 0xeb, 0x82, 0x40,
	0x10, 0xc5, 0xff, 0xea, 0x1f, 0xd1, 0xc1, 0x82, 0xe6, 0x10, 0xe2, 0x29, 0xf6, 0xd4, 0xc9, 0x43,
	0x42, 0x87, 0xae, 0xdd, 0x3c, 0xfa, 0x0d, 0x76, 0xdd, 0x21, 0x56, 0xc8, 0xb1, 0xdd, 0x2d, 0xe8,
	0xdb, 0x07, 0x8b, 0x48, 0xd2, 0x6d, 0xde, 0x7b, 0xcc, 0xfc, 0xe6, 0xc1, 0xc6, 0x91, 0x7d, 0x99,
	0x9e, 0xea, 0xc9, 0xb2, 0x67, 0x4c, 0x06, 0x56, 0x42, 0x41, 0x71, 0xb5, 0x24, 0x3d, 0xb5, 0xac,
	0x3a, 0x7a, 0x20, 0xc2, 0xff, 0x28, 0xef, 0x54, 0x46, 0x87, 0xe8, 0x98, 0x77, 0x61, 0x46, 0x01,
	0x85, 0x26, 0xd7, 0x5b, 0x33, 0x79, 0xc3, 0x3c, 0x96, 0x71, 0xc8, 0x56, 0x1e, 0x56, 0x90, 0xf5,
	0xd2, 0xd3, 0x8d, 0xed, 0xbb, 0x4c, 0x42, 0xbe, 0x68, 0x71, 0x5e, 0x31, 0x1c, 0xee, 0x21, 0x75,
	0x5e, 0xfa, 0xa7, 0x0b, 0x94, 0xac, 0x9b, 0x15, 0x6e, 0x21, 0x36, 0x7a, 0xbe, 0x1e, 0x1b, 0x7d,
	0xba, 0x40, 0xd2, 0xb2, 0xc2, 0x06, 0xf2, 0x65, 0x1d, 0x77, 0xf5, 0xc0, 0xaa, 0xfe, 0x7e, 0xb9,
	0xfa, 0xb1, 0x9c, 0xf8, 0x53, 0x69, 0xe8, 0xd8, 0x7c, 0x02, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xed,
	0x73, 0x9a, 0xf4, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// JobClient is the client API for Job service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobClient interface {
	CreateJob(ctx context.Context, in *CreateJobReq, opts ...grpc.CallOption) (*CreateJobRes, error)
}

type jobClient struct {
	cc grpc.ClientConnInterface
}

func NewJobClient(cc grpc.ClientConnInterface) JobClient {
	return &jobClient{cc}
}

func (c *jobClient) CreateJob(ctx context.Context, in *CreateJobReq, opts ...grpc.CallOption) (*CreateJobRes, error) {
	out := new(CreateJobRes)
	err := c.cc.Invoke(ctx, "/job.Job/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServer is the server API for Job service.
type JobServer interface {
	CreateJob(context.Context, *CreateJobReq) (*CreateJobRes, error)
}

// UnimplementedJobServer can be embedded to have forward compatible implementations.
type UnimplementedJobServer struct {
}

func (*UnimplementedJobServer) CreateJob(ctx context.Context, req *CreateJobReq) (*CreateJobRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJob not implemented")
}

func RegisterJobServer(s *grpc.Server, srv JobServer) {
	s.RegisterService(&_Job_serviceDesc, srv)
}

func _Job_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.Job/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).CreateJob(ctx, req.(*CreateJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Job_serviceDesc = grpc.ServiceDesc{
	ServiceName: "job.Job",
	HandlerType: (*JobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _Job_CreateJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
